---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# The collector is disabled in ../../base as it is still experimental.
patches:
  - target:
      kind: OvnRecon
      name: ovn-recon
    patch: |-
      - op: replace
        path: /spec/collector/enabled
        value: true
