apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # Names a StorageClass and a size.
  - pvc.yaml
  # Names the claim and enables the external route.
  - config.yaml
